import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import "typeface-inter";
import Footer from "@/components/Footer";
import HCaptchaWrapper from "@/components/Captchawrapper";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <HCaptchaWrapper>
          <Navbar />
          <main className="flex-1 flex flex-col items-center justify-center">
            <Toaster position="top-right"/>
            {children}
          </main>
          <Footer />
        </HCaptchaWrapper>
      </body>
    </html>
  );
}
