import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/Navbar';
import 'typeface-inter';
import Footer from '@/components/Footer';
import HCaptchaWrapper from '@/components/Captchawrapper';
import { Toaster } from 'sonner';


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
              <HCaptchaWrapper>
                <Navbar />
                <Toaster position="top-right"/>
                {children}
                <Footer />
                </HCaptchaWrapper>
    </body>
        </html>
    );
}